INSERT INTO "books" VALUES(1,'Девять принцев Амбера');
INSERT INTO "books" VALUES(2,'Ружья Авалона');
INSERT INTO "books" VALUES(3,'Знак Единорога');
INSERT INTO "books" VALUES(4,'Рука Оберона');
INSERT INTO "books" VALUES(5,'Двор Хаоса');
INSERT INTO "books" VALUES(6,'Карты Судьбы');
INSERT INTO "books" VALUES(7,'Кровь Амбера');
INSERT INTO "books" VALUES(8,'Знак Хаоса');
INSERT INTO "books" VALUES(9,'Манюня');
INSERT INTO "books" VALUES(10,'Память Света');
INSERT INTO "books" VALUES(11,'Память Огня');
INSERT INTO "books" VALUES(12,'Грядущая Буря');
INSERT INTO "books" VALUES(13,'Mistborn');

INSERT INTO "authors" VALUES(1,'Роджер Желязны');
INSERT INTO "authors" VALUES(2,'Наринэ Абгарян');
INSERT INTO "authors" VALUES(3,'Роберт Джордан');
INSERT INTO "authors" VALUES(4,'Брендон Сандерсон');

INSERT INTO "authorship" VALUES(1,1);
INSERT INTO "authorship" VALUES(1,2);
INSERT INTO "authorship" VALUES(1,3);
INSERT INTO "authorship" VALUES(1,4);
INSERT INTO "authorship" VALUES(1,5);
INSERT INTO "authorship" VALUES(1,6);
INSERT INTO "authorship" VALUES(1,7);
INSERT INTO "authorship" VALUES(1,8);
INSERT INTO "authorship" VALUES(2,9);
INSERT INTO "authorship" VALUES(3,10);
INSERT INTO "authorship" VALUES(3,11);
INSERT INTO "authorship" VALUES(3,12);
INSERT INTO "authorship" VALUES(4,10);
INSERT INTO "authorship" VALUES(4,11);
INSERT INTO "authorship" VALUES(4,12);
INSERT INTO "authorship" VALUES(4,13);
